### ISSUE TITLE
Seemingly abnormal network connections made by PSOBMLExtract

### ISSUE THREAD

**Issue by eleriaqueen** [Shadowth117/PSOBMLExtract#2]
Hello, I uploaded latest release of your tool to VirusTotal out of curiosity. 

Aside from a False Positive reaction of one of their antivirus I took a look at the report from the VM which ran the app.
For a small tool your app and/or the API it uses seems makes a lot of connections :

HTTP Requests
http://crl.microsoft.com/pki/crl/products/microsoftrootcert.crl
http://www.microsoft.com/pkiops/crl/Microsoft%20Windows%20Verification%20PCA(1).crl
http://go.microsoft.com/fwlink/?LinkId=182227
http://go.microsoft.com/fwlink/?LinkId=151642
http://go.microsoft.com/fwlink/?LinkId=151645

DNS Resolutions
ctldl.windowsupdate.com
au-bg-shim.trafficmanager.net
audownload.windowsupdate.nsatc.net
cs11.wpc.v0cdn.net
hlb.apr-52dd2-0.edgecastdns.net
wu.azureedge.net
wu.ec.azureedge.net
wu.wpc.apr-52dd2.edgecastdns.net
crl.microsoft.com
a1363.dscg.akamai.net
crl.www.ms.akadns.net
www.microsoft.com
e13678.dspb.akamaiedge.net
www.microsoft.com-c-3.edgekey.net
www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net
go.microsoft.com
e11290.dspg.akamaiedge.net
go.microsoft.com.edgekey.net
validation.sls.microsoft.com
validation.sls.trafficmanager.net
genuine.microsoft.com
genuine.microsoft.akadns.net

IP Traffic
72.21.81.240:80 (TCP) 
23.200.147.17:80 (TCP) 
23.33.181.181:80 (TCP) 
104.111.87.125:80 (TCP) 
40.91.72.206:443 (TCP) 
64.4.10.255:80 (TCP)

**Comment by Shadowth117** [comment]
You can look through the code and compile it yourself if you're really concerned. The Windows API Code Pack might be doing it if anything at all.

Regardless, the sites you posted look like random Microsoft sites and you'll find nothing in the code that references them.  Perhaps what's actually happening is Windows is hooking the program and sending back telemetry data or something? Win10 was known for this though it was also added to 7 for instance in later patches. 

Either way, no offense, but just by looking at the websites you yourself posted, you should be able to tell this is nonsense. I'm closing this...

Edit: Also of note, unless you verified it was my program making those connections, it could just be Windows entirely on its own as I suggested before. Naturally, it makes a number of connections for various reasons.
